spring:
  application:
    name: myblog-backend

  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/my_blog?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

# 服务器配置
server:
  port: 8080

# MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.spring0w0.myblog.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 管理员密码
admin:
  password: admin

# 日志配置
logging:
  level:
    com:
      spring0w0:
        myblog: DEBUG